kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: west-cluster

networking:
  podSubnet: "20.20.0.0/16"
  serviceSubnet: "20.96.0.0/12"
  disableDefaultCNI: true
  kubeProxyMode: "nftables"

nodes:
# one node hosting a control plane https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/control-plane-flags/
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        # kube-bench extra args
        profiling: "false"
        audit-log-path: "/var/log/apiserver/audit.log"
        kubelet-certificate-authority: "/etc/kubernetes/pki/ca.crt"
        audit-log-maxage: "30"
        audit-log-maxbackup: "10"
        audit-log-maxsize: "100"
    controllerManager:
      extraArgs:
        profiling: "false"
    scheduler:
      extraArgs:
        profiling: "false"
- role: worker
- role: worker
